
trigger:
  branches:
    include:
      - main

variables:
  resource_group: "demo-rg"
  vm_name: "demo-vm"
  location: "East US"

stages:
  - stage: Terraform
    jobs:
      - job: TerraformInitPlanApply
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - task: UseTerraform@0
            inputs:
              command: 'init'
              workingDirectory: 'terraform'

          - task: UseTerraform@0
            inputs:
              command: 'plan'
              workingDirectory: 'terraform'

          - task: UseTerraform@0
            inputs:
              command: 'apply'
              workingDirectory: 'terraform'
              args: '-auto-approve'

  - stage: Ansible
    dependsOn: Terraform
    jobs:
      - job: RunAnsible
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                sudo apt-get update
                sudo apt-get install -y ansible
                ansible-playbook -i '<VM_PUBLIC_IP>,' ansible/playbook.yml --user azureuser --extra-vars "ansible_password='P@ssword1234!'" --ssh-extra-args='-o StrictHostKeyChecking=no'
