trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'  # Use Microsoft-hosted agent

variables:
  resource_group: "demo-rg"
  vm_name: "demo-vm"
  location: "westeurope"

stages:
  - stage: Terraform
    displayName: "Terraform Deployment"
    jobs:
      - job: TerraformInitPlanApply
        displayName: "Run Terraform"
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: '1.6.6'

          - task: Bash@3
            displayName: "Terraform Init"
            inputs:
              targetType: 'inline'
              script: |
                cd terraform
                terraform init

          - task: Bash@3
            displayName: "Terraform Plan"
            inputs:
              targetType: 'inline'
              script: |
                cd terraform
                terraform plan -var="location=$(location)" -var="resource_group_name=$(resource_group)" -var="vm_name=$(vm_name)"

          - task: Bash@3
            displayName: "Terraform Apply"
            inputs:
              targetType: 'inline'
              script: |
                cd terraform
                terraform apply -var="location=$(location)" -var="resource_group_name=$(resource_group)" -var="vm_name=$(vm_name)" -auto-approve
